CC=avr-gcc
OBJCOPY=avr-objcopy
MCU=atmega328p
F_CPU=16000000UL
CFLAGS=-Wall -Os -mmcu=$(MCU) -DF_CPU=$(F_CPU) -I. -I..

all: avr_test.hex avr_float_test.hex

avr_test.elf: avr_test.c tables.c
	$(CC) $(CFLAGS) $^ -o $@

avr_test.hex: avr_test.elf
	$(OBJCOPY) -O ihex $< $@

avr_float_test.elf: avr_float_test.c ../fast_float.c ../demo/fast_float_tables.c
	$(CC) $(CFLAGS) $^ -o $@

avr_float_test.hex: avr_float_test.elf
	$(OBJCOPY) -O ihex $< $@

clean:
	rm -f *.elf *.hex
